### ISSUE TITLE
New function to get a given color by name

### ISSUE THREAD

**Issue by hguerra** [pedro-andrade-inpe/publish#23]
```lua
local c = color("aqua") -- returns a table { 0, 255, 255}.
c = color("Reds", 2) -- {{254, 224, 210}, {222, 45, 38}}
```

**Comment by pedro-andrade-inpe** [comment]
Is there a library with single color names?

**Comment by hguerra** [comment]
I found some libraries, but they do not meet the requirements. I created my own `Color.lua` with useful functions (https://www.w3.org/wiki/CSS/Properties/color/keywords).
