### ISSUE TITLE
New type Application

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [pedro-andrade-inpe/publish#9]
Implement new type `Application` that creates a web page to visualize the published data. This type will take the following arguments:

1. `file`:  a path o a .tview file.
2. `layers`: a vector of strings with the layers to be exported. As default, it will export all the available layers.
3. `output`: a directory name where the output will be stored.
4. `clean`: a boolean value indicating if the output directory could be automatically removed.
5. `layout`: a `Layout`.

**Comment by hguerra** [comment]
## TODO
- [ ] Remove directories when some error occurs.
- [ ] Apply template in JS files.
